export enum LoaderEnum {
    LIST_HOME = 1,
    COUNT_HOME,
    BACKLOG_SCHEDULE_LIST_SCHEDULED,
    BACKLOG_SCHEDULE_LIST_PLAYED,
    BACKLOG_SCHEDULE_FIND_BY_ID,
    BACKLOG_SCHEDULE_ADD,
    BACKLOG_SCHEDULE_DELETE,
    GAME_DETAIL,
    LOGIN,
    ACHIEVEMENT_DELETE,
    SAVE_GAME,
    DELETE_GAME,
    SAVE_GAME_FROM_EXTERNAL,
    SEARCH_GAME_EXTERNAL,
    ACHIEVEMENT_SAVE,
    SEARCH_ACHIEVEMENT_EXTERNAL,
    SAVE_ACHIEVEMENT_FROM_EXTERNAL
}
